FROM alpine:3.22

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN apk add --no-cache \
    bash \
    build-base \
    ca-certificates \
    curl \
    git \
    musl-dev \
    openssl-dev \
    openssl-libs-static \
    pkgconf \
    sudo \
    zlib-dev \
    zlib-static

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:${PATH}

RUN addgroup -g ${USER_GID} ${USERNAME} && \
    adduser -D -u ${USER_UID} -G ${USERNAME} -h /home/${USERNAME} -s /bin/bash ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99-${USERNAME} && \
    chmod 0440 /etc/sudoers.d/99-${USERNAME} && \
    mkdir -p /home/${USERNAME} /usr/local/cargo /usr/local/rustup /workspaces/cluster-tooling && \
    chown -R ${USER_UID}:${USER_GID} /home/${USERNAME} /usr/local/cargo /usr/local/rustup /workspaces/cluster-tooling

ENV HOME=/home/${USERNAME}

USER ${USERNAME}
WORKDIR /workspaces/cluster-tooling

RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable && \
    rustup component add rustfmt clippy rust-analyzer && \
    rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl && \
    rustc -V && cargo -V

ENV CARGO_PROFILE_RELEASE_LTO=fat \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 \
    CARGO_PROFILE_RELEASE_STRIP=true \
    PKG_CONFIG_ALL_STATIC=1 \
    OPENSSL_STATIC=1 \
    LIBZ_SYS_STATIC=1
